### ISSUE TITLE
Won't update

### ISSUE THREAD

**Issue by asheenlevrai** [rztuc/dokuwiki-plugin-legalnotice#3]
Hello,

According to the extension manager I have version 2014-02-09 installed and version 2015-01-20 is available. According to the changelog on the plugin page (https://www.dokuwiki.org/plugin:legalnotice) version 2016-01-20 should be available.

Hitting the Update button in the extension manager has no effect and I don't dare to uninstall/re-install the plugin fearing that I will loose my settings.

What do you recommend?

Tx
-a-

**Comment by einhirn** [comment]
I recommend that the maintainer should maintain his datestamps in the different locations better.
[x] Done.

Now plugin.info.txt, Dokuwiki Plugin repository and github all say that the last code change was on 2016-01-20...

**Comment by asheenlevrai** [comment]
Thank you so much
I appreciate it.

Best,
-a-
